### ISSUE TITLE
something goes wrong when training

### ISSUE THREAD

**Issue by yanjk3** [Tete-Xiao/ReSim#1]
Thanks for your greate job!!
I meet a problem when running your code. Please give me a hand.
When I input command: 
python main_moco.py -a resnet34 --lr 0.03 --batch-size 256 --dist-url tcp://localhost:10005 --multiprocessing-distributed --world-size 1 --rank 0  --mlp --moco-t 0.2 --aug-plus --cos --epochs 10 ./my_data
Then it turns out:
...
  File "/ReSim-main/moco/models.py", line 306, in forward
    return self._forward_impl(x, return_mocodet_feats=return_mocodet_feats)
  File "/ReSim-main/moco/models.py", line 286, in _forward_impl
    prev_features = self.fpn_lateral5(inst_feats)
  File "/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [256, 2048, 1, 1], expected input[64, 512, 7, 7] to have 2048 channels, but got 512 channels instead
I don't know how to solve this problem. Please help me, thank you very much!

**Comment by cjrd** [comment]
Hey @yanjk3 -- apologies for the delayed response, I just saw this.

The issue is that you're using a resnet34, and our code currently assumes a resnet50 for the output dimensions.

The hacky fix is to change the dimensions here from `[2048, 1024, 512]` to  `[512, 256, 128]` for a resnet 34.
https://github.com/Tete-Xiao/ReSim/blob/2fe526c2ce30d160daf95d3eb53afa00ba9053f7/moco/models.py#L210
